version: '3.8'

services:
  web:
    build: .
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./backend:/usr/src/app/api
      - ./raw_data:/usr/src/input_data
    ports:
      - 5001:5000
    env_file:
      - ./.env.dev
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - .backend/fixed_data:/var/lib/world_factbook/fixed_data
      - ./raw_data:/var/lib/world_factbook/input_data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=world_factbook
      # - PGDATA=/var/lib/postgresql/data/db-files/
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U user -d world_factbook'"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  postgres_data:
